### PR TITLE
Add uf2-samdx1 board config and updated bootloader

### PR DESCRIPTION
**Pull request by Vynce**
This PR contains three commits. Take a closer look at those commit messages for more details.

* First commit brings over a copy of the original bootloader for reference purposes.
* Second commit includes a patched copy of the original bootloader that fixes the issue with automatic uploads. This commit may not be that necessary, but the original bootloader has been in the field for a couple of years and is obviously reliable, so this surgical fix for the automatic bootloader issue may be lower risk than switching to a totally new bootloader.
* Third commit adds a uf2-samdx1 bootloader board config and new up-to-date bootloader binaries. I'd be a bit uncomfortable putting this new bootloader in production without some more eyes/testing.

I've done basic testing with all three of these commits on one of my SAMD51 Thing Plus boards and haven't noticed any obvious issues so far.

I'm more than happy to make any changes, no matter how nitpicky 😊.

This PR addresses issues that were discussed in these two threads:
https://forum.sparkfun.com/viewtopic.php?f=145&t=55574
https://forum.sparkfun.com/viewtopic.php?f=145&t=56457

### CODE REVIEW

**Comment by edspark** [comment]
Excellent read this morning. As circumstance has it, I will not be able to test it for a few days since I'm working from home until next week. Please know that I will test it as soon as I'm able.

**Comment by rbrainey** [comment]
@Vynce Seems like a long time has passed on this PR. I'm chasing an odd issue with reflashing the SAMD51 Thing Plus using Microchip Studio/J-Link. The J-Link programmer stated that the SAMD51 had the Security Bit set.  Attempting to clear it left the '51 in a state where I can no longer connect to it via SWD (this should not happen, but I see other Google search results with a similar outcome).  Were you every programming the Think Plus via SWD?  If so, did you encounter a similar issue?  If so, did you resolve it? Sparkfun hasn't responded to my query.  I may just replace the chip on my board with one straight from the factory, but that is not very elegant.  Your thoughts?

**Comment by Vynce** [comment]
Hi @rbrainey, it *has* been a long time. IIRC, I only programmed the SAMD51 Thing Plus via the UF2 bootloader.

It looks like you need to erase the chip to clear the security bit:
https://forums.adafruit.com/viewtopic.php?t=158387
https://forum.segger.com/index.php/Thread/5256-SOLVED-JLink-unable-to-halt-and-erase-SAMD51-and-SAME54-micros/
https://forum.segger.com/index.php/Thread/6634-SOLVED-Erase-a-SAMD21-with-security-bit-set/
https://learn.adafruit.com/how-to-program-samd-bootloaders/programming-the-bootloader-with-atmel-studio

If you can't get it working, you might have luck posting in the Segger/J-Link forums (?).

**Comment by edspark** [comment]
What a wild journey to come back to this post-covid. I'm not sure what took me away from this pull request all those years ago but a coworker brought this back to my attention. I've been playing with the uf2 bootloader for about two days now and everything seems to check out. Thank you very much for all your work on this. @rbrainey since this a pull request for the uf2 bootloader, I would encourage you to open your issue separately.

**Pull request merged**
